#version 450

layout (local_size_x = 120, local_size_y = 1, local_size_z = 1) in;

layout (binding=0) buffer inputBuffer
{
    uint valueIn[];
};

layout (binding=1) buffer outputBuffer
{
    float valueOut[];
};

void main()
{
    uint iIndex=gl_LocalInvocationID.x + gl_WorkGroupID.x*gl_WorkGroupSize.x;
    //uint iIndex = gl_GlobalInvocationID.x;
    valueOut[iIndex] = valueIn[iIndex] * 10.0;
}
